//! Docker image builder for Claude sessions.
//!
//! Generates a Dockerfile at `~/.config/claude-client/Dockerfile` based on
//! the current `VmConfig` (base image + extra packages), then builds it with
//! `docker build -t <image>`.
//!
//! Requires `docker` on the host.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use tokio::process::Command;
use tracing::info;

/// Always-installed packages (via the package manager detected from the base image).
const ALWAYS_PACKAGES: &[&str] = &["git", "curl", "ca-certificates", "bash"];

// ---------------------------------------------------------------------------
// Public helpers
// ---------------------------------------------------------------------------

/// Check that docker is available on the host.
pub fn check_docker() -> Result<()> {
    which::which("docker").context("docker not found in PATH")?;
    Ok(())
}

/// Write a Dockerfile to `path` based on `base_image` and `extra_packages`.
///
/// The Dockerfile installs Claude Code (via npm) plus any extra packages the
/// user has configured. The package-manager commands adapt to the base image
/// family (Alpine/Debian/Ubuntu → apk/apt-get).
pub async fn write_dockerfile(
    base_image: &str,
    extra_packages: &[String],
    path: &Path,
) -> Result<()> {
    if let Some(dir) = path.parent() {
        tokio::fs::create_dir_all(dir).await?;
    }

    let mut all_pkgs: Vec<&str> = ALWAYS_PACKAGES.to_vec();
    let extra: Vec<&str> = extra_packages.iter().map(|s| s.as_str()).collect();
    all_pkgs.extend_from_slice(&extra);

    let install_cmd = if base_image.contains("alpine") {
        format!(
            "RUN apk add --no-cache nodejs npm {}",
            all_pkgs.join(" ")
        )
    } else {
        // Assume Debian/Ubuntu for everything else
        format!(
            "RUN apt-get update && apt-get install -y --no-install-recommends nodejs npm {} && rm -rf /var/lib/apt/lists/*",
            all_pkgs.join(" ")
        )
    };

    let dockerfile = format!(
        "# Generated by claude-client — edit freely, then run /vmrebuild to apply.\nFROM {base_image}\n{install_cmd}\nRUN npm install -g @anthropic-ai/claude-code\n"
    );

    tokio::fs::write(path, &dockerfile)
        .await
        .with_context(|| format!("write Dockerfile to {}", path.display()))?;

    info!("rootfs: wrote Dockerfile to {}", path.display());
    Ok(())
}

/// Build the Docker image from `dockerfile_path`, tagging it as `image`.
///
/// Captures combined stdout+stderr and returns the last 4 KB of output so the
/// caller can report progress.
pub async fn build(image: &str, dockerfile_path: &Path) -> Result<String> {
    anyhow::ensure!(
        dockerfile_path.exists(),
        "Dockerfile not found at {} — run /vminit first",
        dockerfile_path.display()
    );

    info!("rootfs: building Docker image {image} from {}", dockerfile_path.display());

    let output = Command::new("docker")
        .args([
            "build",
            "--no-cache",
            "-t",
            image,
            "-f",
            dockerfile_path.to_str().unwrap(),
            // Use the Dockerfile's directory as build context (usually has no
            // extra files, so the context is tiny).
            dockerfile_path
                .parent()
                .unwrap_or(Path::new("."))
                .to_str()
                .unwrap(),
        ])
        .output()
        .await
        .context("docker build")?;

    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    // Return last 4 KB for display.
    let tail = if combined.len() > 4096 {
        combined[combined.len() - 4096..].to_string()
    } else {
        combined.clone()
    };

    if output.status.success() {
        info!("rootfs: image {image} built successfully");
        Ok(tail)
    } else {
        anyhow::bail!("docker build failed:\n{tail}")
    }
}

/// Returns the default Dockerfile path (`~/.config/claude-client/Dockerfile`).
pub fn dockerfile_path() -> PathBuf {
    crate::vm::config::VmConfig::dockerfile_path()
}
