//! Docker image builder for Claude sessions.
//!
//! Generates a Dockerfile + entrypoint script at
//! `~/.config/claude-client/Dockerfile` and builds with `docker build`.
//!
//! The entrypoint handles first-run vs resume:
//!   - First run  → `claude --session-id $CLAUDE_SESSION_ID`
//!   - Restart    → `claude --resume    $CLAUDE_SESSION_ID`

use std::path::Path;

use anyhow::{Context, Result};
use tokio::process::Command;
use tracing::info;

const ALWAYS_PACKAGES: &[&str] = &["git", "curl", "ca-certificates", "bash"];

// ---------------------------------------------------------------------------
// Public helpers
// ---------------------------------------------------------------------------

/// Write `Dockerfile` and `entrypoint.sh` to the config dir.
pub async fn write_dockerfile(
    base_image: &str,
    extra_packages: &[String],
    path: &Path,
) -> Result<()> {
    if let Some(dir) = path.parent() {
        tokio::fs::create_dir_all(dir).await?;
    }

    let mut all_pkgs: Vec<&str> = ALWAYS_PACKAGES.to_vec();
    let extra: Vec<&str> = extra_packages.iter().map(|s| s.as_str()).collect();
    all_pkgs.extend_from_slice(&extra);

    let install_cmd = if base_image.contains("alpine") {
        format!("RUN apk add --no-cache nodejs npm {}", all_pkgs.join(" "))
    } else {
        format!(
            "RUN apt-get update && apt-get install -y --no-install-recommends nodejs npm {} && rm -rf /var/lib/apt/lists/*",
            all_pkgs.join(" ")
        )
    };

    // Entrypoint: first run uses --session-id, any container restart uses --resume.
    // Flag file lives in /tmp (writable by any UID, persists in container layer).
    let entrypoint = r#"#!/bin/sh
set -e
if [ -f /tmp/.session_started ]; then
    exec claude --print \
        --input-format stream-json \
        --output-format stream-json \
        --dangerously-skip-permissions \
        --resume "$CLAUDE_SESSION_ID" "$@"
else
    touch /tmp/.session_started
    if [ "$CLAUDE_IS_RESUME" = "1" ]; then
        exec claude --print \
            --input-format stream-json \
            --output-format stream-json \
            --dangerously-skip-permissions \
            --resume "$CLAUDE_SESSION_ID" "$@"
    else
        exec claude --print \
            --input-format stream-json \
            --output-format stream-json \
            --dangerously-skip-permissions \
            --session-id "$CLAUDE_SESSION_ID" "$@"
    fi
fi
"#;

    let dir = path.parent().unwrap();
    let entrypoint_path = dir.join("entrypoint.sh");
    tokio::fs::write(&entrypoint_path, entrypoint)
        .await
        .with_context(|| format!("write entrypoint.sh to {}", entrypoint_path.display()))?;

    let dockerfile = format!(
        "# Generated by claude-client — edit freely, then run /vmrebuild to apply.\n\
         FROM {base_image}\n\
         {install_cmd}\n\
         RUN npm install -g @anthropic-ai/claude-code\n\
         COPY entrypoint.sh /entrypoint.sh\n\
         RUN chmod +x /entrypoint.sh\n\
         ENTRYPOINT [\"/entrypoint.sh\"]\n"
    );

    tokio::fs::write(path, &dockerfile)
        .await
        .with_context(|| format!("write Dockerfile to {}", path.display()))?;

    info!("rootfs: wrote Dockerfile + entrypoint.sh to {}", dir.display());
    Ok(())
}

/// Build the Docker image from `dockerfile_path`, streaming output to `log_tx`.
pub async fn build(
    image: &str,
    dockerfile_path: &Path,
    log_tx: tokio::sync::mpsc::UnboundedSender<String>,
) -> Result<()> {
    anyhow::ensure!(
        dockerfile_path.exists(),
        "Dockerfile not found at {} — run /vmrebuild first",
        dockerfile_path.display()
    );

    info!("rootfs: building Docker image {image} from {}", dockerfile_path.display());

    use tokio::io::{AsyncBufReadExt, BufReader};

    let mut child = Command::new("docker")
        .args([
            "build",
            "--progress=plain",
            "--no-cache",
            "-t",
            image,
            "-f",
            dockerfile_path.to_str().unwrap(),
            dockerfile_path
                .parent()
                .unwrap_or(Path::new("."))
                .to_str()
                .unwrap(),
        ])
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .kill_on_drop(true)
        .spawn()
        .context("docker build")?;

    let stdout = child.stdout.take().unwrap();
    let stderr = child.stderr.take().unwrap();

    let log_tx2 = log_tx.clone();
    tokio::spawn(async move {
        let mut lines = BufReader::new(stdout).lines();
        while let Ok(Some(line)) = lines.next_line().await {
            let _ = log_tx2.send(line);
        }
    });

    let mut lines = BufReader::new(stderr).lines();
    while let Ok(Some(line)) = lines.next_line().await {
        let _ = log_tx.send(line);
    }

    let status = child.wait().await.context("docker build wait")?;
    if status.success() {
        info!("rootfs: image {image} built successfully");
        Ok(())
    } else {
        anyhow::bail!("docker build failed (exit {})", status.code().unwrap_or(-1))
    }
}
